### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pnf3**
updates

### CODE REVIEW

**Comment by twincacca** [comment]
Why are you suggesting this change with regards to that particular journal, Annals of case reports, given proofs of acceptance to publish without peer review? Any particular reason?

**Comment by pnf3** [comment]
Thank you for raising this question regarding *Annals of Case Reports* and
the decision to provide acceptance proofs without traditional peer review.
There are valid reasons for such a process that can benefit both authors
and the broader medical community:

   1.

   *Efficient Publication Process*: In fields like case reporting, timely
   publication can be crucial, especially when the cases involve unique
   findings or urgent clinical insights. Providing acceptance proofs without
   delay ensures that important information reaches the scientific community
   faster, potentially influencing patient care and clinical decision-making
   more promptly.
   2.

   *Focus on Clinical Value*: Case reports often present novel or rare
   medical conditions where the primary goal is to share experiences rather
   than test hypotheses. In these situations, peer review may not always be
   necessary to validate the clinical relevance of the case. By streamlining
   the process, *Annals of Case Reports* ensures that valuable case studies
   are shared quickly, allowing clinicians to learn from rare or unusual
   patient outcomes.
   3.

   *Quality Editorial Oversight*: Although the journal may bypass
   traditional peer review, it likely employs a robust editorial process to
   ensure the content is medically sound and well-presented. This editorial
   oversight ensures that while the review process is expedited, the quality
   and relevance of the cases remain high.
   4.

   *Enhancing Research Accessibility*: Many journals have cumbersome
   submission processes that can be a barrier for busy clinicians. Offering a
   more flexible approach, as *Annals of Case Reports* does, encourages the
   submission of cases that might otherwise go unreported, thereby enriching
   the literature with more real-world clinical experiences.

In summary, by offering a streamlined approach to publication, *Annals of
Case Reports* is positioning itself as a responsive and accessible platform
for disseminating important clinical findings quickly and following
strict peer review for most of Case Reports. This can have a positive
impact on patient care and the ongoing education of medical professionals.

As soon as Possible Accept that request

**Comment by twincacca** [comment]
But isn't it quite opposed to what stated on your journal webpage? 
annals_case_reports_guidelines
annals_case_reports_reply

**Comment by pnf3** [comment]
Please carefully read the email and webpage content for clarification.
First, we seek the author's preference: whether they require peer review or
prefer to publish without peer review in urgent cases. As stated on our
website, we are committed to providing peer review for all submissions if
the authors request it.

To illustrate this clearly, consider the example of a COVID-19 case report
during the initial stages of the pandemic. In this instance, the authors
recognized the urgency of the situation and requested immediate
publication, given the global threat posed by the virus. Publishing this
case quickly allowed doctors and researchers to understand it better,
potentially aiding in the development of treatments and vaccines.

Had this case been subjected to the traditional peer review process, which
can take several months, valuable time would have been lost, and the virus
could have spread even more rapidly. This example demonstrates why we offer
an expedited publication option for emergency cases, ensuring timely
dissemination of critical information while also respecting the option for
peer review when needed.

**Comment by twincacca** [comment]
Then you should make a blog and see how many like your opinions. Science should get exposed to and stand challenge and critics, that's the very essence of it.

And importantly, you probably should update your policy page on the journal web page, as it does give a quite different description, not really in line with what you claim:

policy

**Pull request closed without merging**
